/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polyvi_xface_util_XNativeBridge */

#ifndef _Included_com_polyvi_xface_util_XNativeBridge
#define _Included_com_polyvi_xface_util_XNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_polyvi_xface_util_XNativeBridge
 * Method:    chmod
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_polyvi_xface_util_XNativeBridge_chmod
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
