/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polyvi_xface_util_XSecurityUtils */

#ifndef _Included_com_polyvi_xface_util_XUtils
#define _Included_com_polyvi_xface_util_XUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_polyvi_xface_util_XSecurityUtils
 * Method:    generateKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_polyvi_xface_util_XKeyGenerator_generateKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
